version: '3'

services:
  bids-tryworks_external_dicom_db:
    #user: $UID:$GID
    image: postgres:11.4
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5223:5432
  bids-tryworks_external_dicom:
    build:
      context: .
      dockerfile: Dockerfile
    #user: $UID:$GID
    tty: true
    command: bash -c "sleep 10
              && python3 /bids-tryworks/manage.py makemigrations dicoms --settings=bids-tryworks.docker
              && python3 /bids-tryworks/manage.py migrate --settings=bids-tryworks.docker
              && python3 /bids-tryworks/manage.py runserver 0.0.0.0:8000 --settings=bids-tryworks.docker"
      #&& python3 /bids-tryworks/manage.py autoindex </dev/null &>/dev/null &
    volumes:
      # code folder
      - /${CODE_FOLDER}:/bids-tryworks
      # location of dicoms to index/convert from
      - /${BASE_DICOM_DIR}:/MOUNTED_FOLDER/BASE_DICOM_DIR
      # folder for converted subjects
      - /${CONVERTED_FOLDER}:/MOUNTED_FOLDER/CONVERTED_FOLDER
      # Path to Logs (not currently used but it can't hurt
      - /${LOG_FOLDER}:/MOUNTED_FOLDER/LOG_FOLDER
      # Path to folder for dcm2bids conversion jsons
      - /${DCM2BIDS_FILES}:/MOUNTED_FOLDER/DCM2BIDS_FILES
    ports:
      - "8870:8000"
    depends_on:
      - bids-tryworks_external_dicom_db
  bids-tryworks_external_dicom_autoindexer:
    build:
      context: .
      dockerfile: Dockerfile
    #user: $UID:$GID
    tty: true
    command: bash -c "sleep 5
      && python3 /bids-tryworks/manage.py makemigrations dicoms --settings=bids-tryworks.docker
      && python3 /bids-tryworks/manage.py migrate --settings=bids-tryworks.docker
      && python3 /bids-tryworks/manage.py autoindex --settings=bids-tryworks.docker"
    volumes:
      # code folder
      - /${CODE_FOLDER}:/bids-tryworks
      # location of dicoms to index/convert from
      - /${BASE_DICOM_DIR}:/MOUNTED_FOLDER/BASE_DICOM_DIR
      # folder for converted subjects
      - /${CONVERTED_FOLDER}:/MOUNTED_FOLDER/CONVERTED_FOLDER
      # Path to Logs (not currently used but it can't hurt
      - /${LOG_FOLDER}:/MOUNTED_FOLDER/LOG_FOLDER
      # Path to folder for dcm2bids conversion jsons
      - /${DCM2BIDS_FILES}:/MOUNTED_FOLDER/DCM2BIDS_FILES
    ports:
      - "8860:8001"
    depends_on:
      - bids-tryworks_external_dicom_db
  bids-tryworks_external_dicom_daily_indexer:
    build:
      context: .
      dockerfile: Dockerfile
    #user: $UID:$GID
    tty: true
    command: bash -c "sleep 5
      && python3 /bids-tryworks/manage.py makemigrations dicoms --settings=bids-tryworks.docker
      && python3 /bids-tryworks/manage.py migrate --settings=bids-tryworks.docker
      && python3 /bids-tryworks/manage.py dailyindex --settings=bids-tryworks.docker"
    volumes:
      # code folder
      - /${CODE_FOLDER}:/bids-tryworks
      # location of dicoms to index/convert from
      - /${BASE_DICOM_DIR}:/MOUNTED_FOLDER/BASE_DICOM_DIR
      # folder for converted subjects
      - /${CONVERTED_FOLDER}:/MOUNTED_FOLDER/CONVERTED_FOLDER
      # Path to Logs (not currently used but it can't hurt
      - /${LOG_FOLDER}:/MOUNTED_FOLDER/LOG_FOLDER
      # Path to folder for dcm2bids conversion jsons
      - /${DCM2BIDS_FILES}:/MOUNTED_FOLDER/DCM2BIDS_FILES
    ports:
      - "8861:8002"
    depends_on:
      - bids-tryworks_external_dicom_db
